---

language: go
sudo: false
dist: trusty

go:
  - 1.14.x
  - 1.13.x
  - master

before_script: make prepare

script:
  - make all
  - make lint

matrix:
  allow_failures:
    - go: master
    - go: 1.14.x  # because of golangci-lint
